- name: Demo on Variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: Demo with Quotes on Variables
  hosts: all
  vars:
    play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: "{{ URL }} is the URL"

