- name: Demo on Loops
  hosts: localhost
  tasks:
    - name: Print Fruit name with list of values loop
      ansible.builtin.debug:
        msg: Fruit name = {{item}}
      loop:
        - apple
        - banana
        - orange
    - name: Print Fruit name with list of map loop
      ansible.builtin.debug:
        msg: Fruit name = {{item.name}}, Quantity = {{item.quantity}}
      loop:
        - { name: "apple", quantity: 100 }
        - { name: "orange", quantity: 70 }
        - { name: "banana", quantity: 30 }