- name: Demo on pulling aws parameters and secrets
  hosts: localhost
  vars:
    PARAMETER: "{{ lookup('aws_ssm', 'roboshop.test1', region='us-east-1') }}"
    SECRET: "{{ lookup('amazon.aws.aws_secret', 'roboshop/all-secrets', region='us-east-1') }}"
  tasks:
    - name: Pull secret
      debug: msg="{{ SECRET.ROBOSHOP_MYSQL_PASSWORD }}"
    - name: Pull parameter
      debug: msg="{{ PARAMETER }}"

